# Form implementation generated from reading ui file '.\templates\dlgBuscaLocal.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgBuscaLocal(object):
    def setupUi(self, dlgBuscaLocal):
        dlgBuscaLocal.setObjectName("dlgBuscaLocal")
        dlgBuscaLocal.resize(400, 300)
        dlgBuscaLocal.setMinimumSize(QtCore.QSize(400, 300))
        dlgBuscaLocal.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/icono.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgBuscaLocal.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(dlgBuscaLocal)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.cmbBuscalocal = QtWidgets.QComboBox(parent=dlgBuscaLocal)
        self.cmbBuscalocal.setEditable(True)
        self.cmbBuscalocal.setObjectName("cmbBuscalocal")
        self.verticalLayout.addWidget(self.cmbBuscalocal)
        self.btnGenInforme = QtWidgets.QPushButton(parent=dlgBuscaLocal)
        self.btnGenInforme.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnGenInforme.setObjectName("btnGenInforme")
        self.verticalLayout.addWidget(self.btnGenInforme, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lblEligeLocal = QtWidgets.QLabel(parent=dlgBuscaLocal)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEligeLocal.setFont(font)
        self.lblEligeLocal.setObjectName("lblEligeLocal")
        self.horizontalLayout.addWidget(self.lblEligeLocal)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)

        self.retranslateUi(dlgBuscaLocal)
        QtCore.QMetaObject.connectSlotsByName(dlgBuscaLocal)

    def retranslateUi(self, dlgBuscaLocal):
        _translate = QtCore.QCoreApplication.translate
        dlgBuscaLocal.setWindowTitle(_translate("dlgBuscaLocal", "Elige Localidad"))
        self.btnGenInforme.setText(_translate("dlgBuscaLocal", "Generar Informe"))
        self.lblEligeLocal.setText(_translate("dlgBuscaLocal", "Elige Localidad"))
