# Form implementation generated from reading ui file '.\templates\dlgGestionprop.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgTipoProp(object):
    def setupUi(self, dlgTipoProp):
        dlgTipoProp.setObjectName("dlgTipoProp")
        dlgTipoProp.resize(400, 300)
        dlgTipoProp.setMinimumSize(QtCore.QSize(400, 300))
        dlgTipoProp.setMaximumSize(QtCore.QSize(400, 300))
        self.frame = QtWidgets.QFrame(parent=dlgTipoProp)
        self.frame.setGeometry(QtCore.QRect(30, 40, 339, 112))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 270, 20))
        self.label.setMinimumSize(QtCore.QSize(270, 20))
        self.label.setMaximumSize(QtCore.QSize(270, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 150, 20))
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.layoutWidget = QtWidgets.QWidget(parent=dlgTipoProp)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 210, 158, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltatipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltatipoprop.setObjectName("btnAltatipoprop")
        self.horizontalLayout.addWidget(self.btnAltatipoprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)

        self.retranslateUi(dlgTipoProp)
        QtCore.QMetaObject.connectSlotsByName(dlgTipoProp)

    def retranslateUi(self, dlgTipoProp):
        _translate = QtCore.QCoreApplication.translate
        dlgTipoProp.setWindowTitle(_translate("dlgTipoProp", "Dialog"))
        self.label.setText(_translate("dlgTipoProp", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltatipoprop.setText(_translate("dlgTipoProp", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlgTipoProp", "Eliminar"))
